[build]
  functions = "netlify/functions"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "same-origin"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=31536000, immutable"
